class Emoji:
    pencil2 = "✏️"
    calendar = "📅"
    card_index_dividers = "🗂"
    back = "◀️"
    thief = "🦹🏻"
    book = "📖"
    clock9 = "🕘"
    clock330 = "🕞"
    x = "❌"
    house = "🏡"
    pushpin = "📌"
